<?php


 function autoload_3142cca9015b6c7363eb9e2e5f3b75ba($class)
{
    $classes = array(
        'AscioService' => __DIR__ .'/AscioService.php',
        'CreateOrder' => __DIR__ .'/CreateOrder.php',
        'CreateOrderResponse' => __DIR__ .'/CreateOrderResponse.php',
        'ValidateOrder' => __DIR__ .'/ValidateOrder.php',
        'ValidateOrderResponse' => __DIR__ .'/ValidateOrderResponse.php',
        'GetOrder' => __DIR__ .'/GetOrder.php',
        'GetOrderResponse' => __DIR__ .'/GetOrderResponse.php',
        'GetOrders' => __DIR__ .'/GetOrders.php',
        'GetOrdersResponse' => __DIR__ .'/GetOrdersResponse.php',
        'GetMark' => __DIR__ .'/GetMark.php',
        'GetMarkResponse' => __DIR__ .'/GetMarkResponse.php',
        'GetDefensive' => __DIR__ .'/GetDefensive.php',
        'GetDefensiveResponse' => __DIR__ .'/GetDefensiveResponse.php',
        'GetNameWatch' => __DIR__ .'/GetNameWatch.php',
        'GetNameWatchResponse' => __DIR__ .'/GetNameWatchResponse.php',
        'GetSslCertificate' => __DIR__ .'/GetSslCertificate.php',
        'GetSslCertificateResponse' => __DIR__ .'/GetSslCertificateResponse.php',
        'GetMessages' => __DIR__ .'/GetMessages.php',
        'GetMessagesResponse' => __DIR__ .'/GetMessagesResponse.php',
        'PollQueue' => __DIR__ .'/PollQueue.php',
        'PollQueueResponse' => __DIR__ .'/PollQueueResponse.php',
        'AckQueueMessage' => __DIR__ .'/AckQueueMessage.php',
        'AckQueueMessageResponse' => __DIR__ .'/AckQueueMessageResponse.php',
        'GetQueueMessage' => __DIR__ .'/GetQueueMessage.php',
        'GetQueueMessageResponse' => __DIR__ .'/GetQueueMessageResponse.php',
        'UploadDocumentation' => __DIR__ .'/UploadDocumentation.php',
        'UploadDocumentationResponse' => __DIR__ .'/UploadDocumentationResponse.php',
        'UploadMessage' => __DIR__ .'/UploadMessage.php',
        'UploadMessageResponse' => __DIR__ .'/UploadMessageResponse.php',
        'AbstractOrderRequest' => __DIR__ .'/AbstractOrderRequest.php',
        'OrderType' => __DIR__ .'/OrderType.php',
        'MarkOrderRequest' => __DIR__ .'/MarkOrderRequest.php',
        'AbstractMark' => __DIR__ .'/AbstractMark.php',
        'MarkServiceType' => __DIR__ .'/MarkServiceType.php',
        'NotificationFrequencyType' => __DIR__ .'/NotificationFrequencyType.php',
        'Registrant' => __DIR__ .'/Registrant.php',
        'Contact' => __DIR__ .'/Contact.php',
        'Extensions' => __DIR__ .'/Extensions.php',
        'KeyValue' => __DIR__ .'/KeyValue.php',
        'SslCertificateOrderRequest' => __DIR__ .'/SslCertificateOrderRequest.php',
        'SslCertificate' => __DIR__ .'/SslCertificate.php',
        'WebServerType' => __DIR__ .'/WebServerType.php',
        'TreatyOrStatuteMark' => __DIR__ .'/TreatyOrStatuteMark.php',
        'Trademark' => __DIR__ .'/Trademark.php',
        'CourtValidatedMark' => __DIR__ .'/CourtValidatedMark.php',
        'SecurityHeaderDetails' => __DIR__ .'/SecurityHeaderDetails.php',
        'ArrayOfMarkOrderDocument' => __DIR__ .'/ArrayOfMarkOrderDocument.php',
        'MarkOrderDocument' => __DIR__ .'/MarkOrderDocument.php',
        'Attachment' => __DIR__ .'/Attachment.php',
        'MarkOrderDocType' => __DIR__ .'/MarkOrderDocType.php',
        'DefensiveOrderRequest' => __DIR__ .'/DefensiveOrderRequest.php',
        'NameWatchOrderRequest' => __DIR__ .'/NameWatchOrderRequest.php',
        'NameWatch' => __DIR__ .'/NameWatch.php',
        'Defensive' => __DIR__ .'/Defensive.php',
        'AbstractResponse' => __DIR__ .'/AbstractResponse.php',
        'OrderInfo' => __DIR__ .'/OrderInfo.php',
        'OrderStatusType' => __DIR__ .'/OrderStatusType.php',
        'GetOrderRequest' => __DIR__ .'/GetOrderRequest.php',
        'GetOrdersRequest' => __DIR__ .'/GetOrdersRequest.php',
        'ArrayOfOrderStatusType' => __DIR__ .'/ArrayOfOrderStatusType.php',
        'ArrayOfOrderType' => __DIR__ .'/ArrayOfOrderType.php',
        'ArrayOfObjectType' => __DIR__ .'/ArrayOfObjectType.php',
        'ObjectType' => __DIR__ .'/ObjectType.php',
        'SearchOrderSortType' => __DIR__ .'/SearchOrderSortType.php',
        'PagingInfo' => __DIR__ .'/PagingInfo.php',
        'ArrayOfOrderInfo' => __DIR__ .'/ArrayOfOrderInfo.php',
        'GetMarkRequest' => __DIR__ .'/GetMarkRequest.php',
        'MarkInfo' => __DIR__ .'/MarkInfo.php',
        'GetDefensiveRequest' => __DIR__ .'/GetDefensiveRequest.php',
        'DefensiveInfo' => __DIR__ .'/DefensiveInfo.php',
        'GetNameWatchRequest' => __DIR__ .'/GetNameWatchRequest.php',
        'NameWatchInfo' => __DIR__ .'/NameWatchInfo.php',
        'GetSslCertificateRequest' => __DIR__ .'/GetSslCertificateRequest.php',
        'SslCertificateInfo' => __DIR__ .'/SslCertificateInfo.php',
        'GetMessagesRequest' => __DIR__ .'/GetMessagesRequest.php',
        'ArrayOfMessage' => __DIR__ .'/ArrayOfMessage.php',
        'Message' => __DIR__ .'/Message.php',
        'ArrayOfAttachment' => __DIR__ .'/ArrayOfAttachment.php',
        'MessageType' => __DIR__ .'/MessageType.php',
        'PollQueueRequest' => __DIR__ .'/PollQueueRequest.php',
        'QueueMessage' => __DIR__ .'/QueueMessage.php',
        'ArrayOfErrorCode' => __DIR__ .'/ArrayOfErrorCode.php',
        'ErrorCode' => __DIR__ .'/ErrorCode.php',
        'AckQueueMessageRequest' => __DIR__ .'/AckQueueMessageRequest.php',
        'GetQueueMessageRequest' => __DIR__ .'/GetQueueMessageRequest.php',
        'UploadDocumentationRequest' => __DIR__ .'/UploadDocumentationRequest.php',
        'UploadMessageRequest' => __DIR__ .'/UploadMessageRequest.php',
        'ArrayOfstring' => __DIR__ .'/ArrayOfstring.php',
        'ArrayOfint' => __DIR__ .'/ArrayOfint.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_3142cca9015b6c7363eb9e2e5f3b75ba');

// Do nothing. The rest is just leftovers from the code generation.
{
}
